#!/usr/bin/env python3
"""cdkey_reg.py -- reference encoder/decoder for the CD-key FILES of Diablo II 1.14d.

(The name is historical: the keys are NOT stored in the registry. Game.exe 1.14d
loads them with Storm SFileLoadFile from the MPQ chain, see RE notes below.)

  classic key : "font\\font.gid"  else  data\\global\\sfx\\cursor\\wavindx.wav
  owner name  : "font\\font.clh"  else  data\\global\\sfx\\cursor\\curindx.wav
  LoD key     : data\\global\\chars\\am\\cof\\amblxbow.cof   (only if expansion)

Loader  Game.exe!0x5234D0, per-file decrypt+check 0x5232B0 (ecx=buf, edi=size)
Decrypt 0x522E10 (ecx=buf, edx=size, [esp+4]=password) -> plaintext length or 0
Encrypt 0x523060 (ecx=buf, edx=len, [esp+4]=bufsize, [esp+8]=password) -- dead
        code in Game.exe (no xref), but it is the exact counterpart.
Password 0x522BC0: srand(0x150B), 19 non-zero low bytes of rand(), NUL.
Setup   0x522C30: srand(0x4FA7), 112 rand() bytes, XOR with SHA-0'(pw cyclic 64B)
        -> 3 IDEA keys (bytes 0..47) + SHA-0' state = compress(IV, bytes 48..111).
Cipher  per 64-byte block: K = current SHA state (20B); C[j]=P[j]+K[(63-j)%20];
        every 8th block (blk%8==0) additionally IDEA-encrypt 8 x 8B (ctx 0, LE words);
        every 16th block (blk%16==0) the state absorbs the PLAINTEXT block.
Trailer 8 bytes: state[0:4] | 0x00 | last-block length | 0x0000.
Nothing machine-dependent (no computer/user name, no volume serial).

No real key is ever used here: only fake keys generated by the self-test.
"""
import os, struct, sys

M32 = 0xFFFFFFFF

# ---------------------------------------------------------------- MSVC rand
class MsRand:
    def __init__(self, seed): self.s = seed & M32
    def rand(self):
        self.s = (self.s * 0x343FD + 0x269EC3) & M32
        return (self.s >> 16) & 0x7FFF

def password():                          # Game.exe!0x522BC0 (edx = 0x14)
    r = MsRand(0x150B); out = bytearray()
    while len(out) < 0x13:
        b = r.rand() & 0xFF
        if b: out.append(b)
    return bytes(out) + b"\0"

# ------------------------------------------- SHA-0 variant (0x523AF0 / 0x524200)
def _sar(x, n):
    x &= M32
    return ((x - (1 << 32)) >> n) & M32 if x & 0x80000000 else x >> n
def _rol5(x):  return ((x << 5) & M32) | _sar(x, 27)      # SIGNED shift, as in the binary
def _rol30(x): return ((x << 30) & M32) | _sar(x, 2)

def sha_compress(state, block64):
    W = list(struct.unpack("<16I", block64))
    for t in range(16, 80):                      # no rotation: SHA-0 schedule
        W.append(W[t-3] ^ W[t-8] ^ W[t-14] ^ W[t-16])
    a, b, c, d, e = state
    for t in range(80):
        if t < 20:   f, k = (b & c) | (~b & d), 0x5A827999
        elif t < 40: f, k = b ^ c ^ d, 0x6ED9EBA1
        elif t < 60: f, k = (b & c) | (b & d) | (c & d), 0x8F1BBCDC
        else:        f, k = b ^ c ^ d, 0xCA62C1D6
        tmp = (_rol5(a) + (f & M32) + W[t] + e + k) & M32
        a, b, c, d, e = tmp, a, _rol30(b), c, d
    return [(x + y) & M32 for x, y in zip(state, (a, b, c, d, e))]

SHA_IV = [0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0]
def sha_bytes(state): return struct.pack("<5I", *state)

# ------------------------------------------------------------ IDEA (LE words)
def _mul(a, b):
    a &= 0xFFFF; b &= 0xFFFF
    if a == 0: return (1 - b) & 0xFFFF
    if b == 0: return (1 - a) & 0xFFFF
    p = a * b; lo, hi = p & 0xFFFF, p >> 16
    return (lo - hi + (lo < hi)) & 0xFFFF
def _inv(x):
    return x if x <= 1 else pow(x, -1, 0x10001) & 0xFFFF

def idea_expand(key16):                   # 0x524360 (PGP ideaExpandKey)
    ek = list(struct.unpack("<8H", key16)) + [0] * 44
    base, i = 0, 0
    for j in range(8, 52):
        i += 1
        ek[base + i + 7] = ((ek[base + (i & 7)] << 9) | (ek[base + ((i + 1) & 7)] >> 7)) & 0xFFFF
        base += i & 8; i &= 7
    return ek

def idea_invert(ek):                      # 0x5243E0 (PGP ideaInvertKey)
    dk = [0] * 52; p = 52; e = iter(ek)
    def push(v):
        nonlocal p; p -= 1; dk[p] = v & 0xFFFF
    t1 = _inv(next(e)); t2 = -next(e); t3 = -next(e); push(_inv(next(e))); push(t3); push(t2); push(t1)
    for _ in range(7):
        t1 = next(e); push(next(e)); push(t1)
        t1 = _inv(next(e)); t2 = -next(e); t3 = -next(e); push(_inv(next(e))); push(t2); push(t3); push(t1)
    t1 = next(e); push(next(e)); push(t1)
    t1 = _inv(next(e)); t2 = -next(e); t3 = -next(e); push(_inv(next(e))); push(t3); push(t2); push(t1)
    return dk

def idea_block(k, blk8):                  # 0x524540
    x1, x2, x3, x4 = struct.unpack("<4H", blk8); i = 0
    for _ in range(8):
        x1 = _mul(x1, k[i]); x2 = (x2 + k[i+1]) & 0xFFFF
        x3 = (x3 + k[i+2]) & 0xFFFF; x4 = _mul(x4, k[i+3])
        t0 = _mul(x3 ^ x1, k[i+4]); t1 = _mul(((x4 ^ x2) + t0) & 0xFFFF, k[i+5])
        t0 = (t0 + t1) & 0xFFFF
        x1 ^= t1; x4 ^= t0; x2, x3 = x3 ^ t1, x2 ^ t0
        i += 6
    return struct.pack("<4H", _mul(x1, k[48]), (x3 + k[49]) & 0xFFFF,
                       (x2 + k[50]) & 0xFFFF, _mul(x4, k[51]))

# ------------------------------------------------------------------ setup
def setup(pw, encrypt):                   # 0x522C30
    r = MsRand(0x4FA7)
    R = bytearray(r.rand() & 0xFF for _ in range(0x70))
    blk = bytearray(); i = 0
    while len(blk) < 64:
        if pw[i] == 0: i = 0
        blk.append(pw[i]); i += 1
    d = sha_bytes(sha_compress(SHA_IV, bytes(blk)))
    for j in range(0x70): R[j] ^= d[j % 20]
    ek = idea_expand(bytes(R[0:16]))       # only context 0 is ever used
    keys = ek if encrypt else idea_invert(ek)
    state = sha_compress(SHA_IV, bytes(R[0x30:0x70]))
    return keys, state

# --------------------------------------------------------- encrypt / decrypt
def encrypt(plain, pw=None):              # 0x523060
    pw = pw or password(); keys, st = setup(pw, True)
    out = bytearray(); last = 0
    for b in range(0, len(plain), 64):
        n = min(64, len(plain) - b); last = n
        P = plain[b:b+n] + b"\0" * (64 - n); K = sha_bytes(st); idx = b // 64
        if idx & 0xF == 0: st = sha_compress(st, P)
        C = bytes((P[j] + K[(0x3F - j) % 20]) & 0xFF for j in range(64))
        if idx & 7 == 0: C = b"".join(idea_block(keys, C[j:j+8]) for j in range(0, 64, 8))
        out += C
    out += sha_bytes(st)[0:4] + bytes([0, last & 0xFF, 0, 0])
    return bytes(out)

def decrypt(blob, pw=None):               # 0x522E10 ; returns (length, bytes) -- length 0 = rejected
    pw = pw or password(); keys, st = setup(pw, False)
    size = len(blob)
    if size <= 8 or (size - 8) & 0x3F: return 0, b""
    size -= 8; out = bytearray()
    for b in range(0, size, 64):
        T = blob[b:b+64]; K = sha_bytes(st); idx = b // 64
        C = b"".join(idea_block(keys, T[j:j+8]) for j in range(0, 64, 8)) if idx & 7 == 0 else T
        P = bytes((C[j] - K[(0x3F - j) % 20]) & 0xFF for j in range(64))
        if idx & 0xF == 0: st = sha_compress(st, P)
        out += P
    tr = blob[size:]
    if tr[4] != 0 or tr[0:4] != sha_bytes(st)[0:4]: return 0, b""
    n = size - 64 + tr[5]
    return n, bytes(out[:n])

def game_accepts(blob):                   # 0x5232B0 : decrypt + NUL + strnlen(<=0x80)
    n, p = decrypt(blob)
    if n == 0 or n >= len(blob): return None
    s = p.split(b"\0", 1)[0]
    return s

KEY_FILES = {
    "classic": ("font\\font.gid", "data\\global\\sfx\\cursor\\wavindx.wav"),
    "owner":   ("font\\font.clh", "data\\global\\sfx\\cursor\\curindx.wav"),
    "lod":     (None,             "data\\global\\chars\\am\\cof\\amblxbow.cof"),
}

def make_blob(text):
    """Plaintext = ASCII + NUL (27 bytes for a 26-char key) -> 72-byte blob,
    the size observed in stock MPQs. The game accepts with or without the NUL."""
    return encrypt(text.encode("ascii") + b"\0")

# --------------------------------------------------------------- self-test
def fake_key(rng):
    alpha = "246789BCDEFGHJKMNPRTVWXYZ"
    return "".join(alpha[b % 25] for b in rng(26))

if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "enc":
        print(encrypt(bytes.fromhex(sys.argv[2])).hex()); sys.exit(0)
    if len(sys.argv) >= 3 and sys.argv[1] == "dec":
        n, p = decrypt(bytes.fromhex(sys.argv[2])); print(n, p.hex()); sys.exit(0)
    assert password().hex() == "de882a14db23e38fb3fb7ba422eb341822157a00"
    ok = 0
    for L in list(range(1, 140)) + [511, 512, 513, 1023, 1024, 1025, 1100]:
        p = os.urandom(L); b = encrypt(p)
        assert len(b) == ((L + 63) // 64) * 64 + 8
        assert decrypt(b) == (L, p), L
        ok += 1
    k = fake_key(os.urandom); b = make_blob(k)
    assert len(b) == 72 and game_accepts(b) == k.encode()
    bad = bytearray(b); bad[3] ^= 1
    assert game_accepts(bytes(bad)) is None
    print("PASS roundtrip %d lengths, fake key blob 72 bytes, tamper rejected" % ok)
