#!/usr/bin/env python3
# Bakes the radial menu PNGs (third_party/assets/radial_menu/) into raw RGBA8,
# embedded in src/platform/radial_menu_assets.h — no PNG dependency at ARM
# build time, this generated header is the only artifact the build uses.
#
# The geometric constants (TIP_FRAC, ICON_CX/CY, ratio) are MEASURED directly
# from the pixels of wedge-normal.png, NOT copied from the kit's README: the
# README states a 300:345 (portrait) ratio, but the actual file is 674x549
# (landscape) once cropped to its alpha channel — too large a gap to be
# rounding noise. Trusting the pixels avoids propagating a documentation error.
#
# Regenerate after any change to the source PNGs:
#   python3 tools/gen_radial_assets.py
import numpy as np
from PIL import Image
import os

SRC = os.path.join(os.path.dirname(__file__), "..", "third_party", "assets", "radial_menu")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "platform", "radial_menu_assets.h")

# Target display size (960x544 screen) — chosen for a menu about 340px in
# diameter, centered on screen, with a real center hole.
WEDGE_W = 130
HOLE_RADIUS = 70
ICON_SIZE = 48
N = 7

# Order of the 7 sectors, clockwise from the top (theta_i = i * 360/7).
# Arbitrary choice (no D2 convention): skills at the top, then clockwise.
ORDER = ["competences", "quetes", "carte", "equipement", "chat", "guilde", "perso"]
VK = {  # injected VK key
    "competences": 0x54, "quetes": 0x51, "carte": 0x09, "equipement": 0x49,
    "chat": 0x0D, "guilde": 0x50, "perso": 0x43,
}
# competences = T by default in D2 1.14d, not S (verified on console — S opens
# something else / does nothing useful; the in-game key config confirms T).
# The virtual keyboard is not in the radial menu (it's bound directly to
# Triangle instead) — "perso" (character sheet, C key) takes its place.


def alpha_bbox(im, thresh):
    a = np.array(im.split()[-1])
    ys, xs = np.where(a > thresh)
    return int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())


def load_wedge():
    wn = Image.open(os.path.join(SRC, "wedge-normal.png")).convert("RGBA")
    wg = Image.open(os.path.join(SRC, "wedge-glow.png")).convert("RGBA")
    x0, y0, x1, y1 = alpha_bbox(wn, 128)
    w, h = x1 - x0 + 1, y1 - y0 + 1

    arr = np.array(wn)[y0:y1 + 1, x0:x1 + 1, :].astype(np.float64)
    alpha = arr[:, :, 3]
    ys, xs = np.mgrid[0:h, 0:w]
    tot = alpha.sum()
    icon_cx = float((xs * alpha).sum() / tot / w)
    icon_cy = float((ys * alpha).sum() / tot / h)

    cxi = w // 2
    band = alpha[:, max(0, cxi - 3):cxi + 4]
    tip_frac = float(np.where((band > 128).any(axis=1))[0].max() / h)

    wedge_h = round(WEDGE_W * h / w)
    wn_crop = wn.crop((x0, y0, x1 + 1, y1 + 1)).resize((WEDGE_W, wedge_h), Image.LANCZOS)
    wg_crop = wg.crop((x0, y0, x1 + 1, y1 + 1)).resize((WEDGE_W, wedge_h), Image.LANCZOS)
    return wn_crop, wg_crop, wedge_h, tip_frac, icon_cx, icon_cy


def load_icon(name):
    im = Image.open(os.path.join(SRC, name + ".png")).convert("RGBA")
    x0, y0, x1, y1 = alpha_bbox(im, 20)
    crop = im.crop((x0, y0, x1 + 1, y1 + 1))
    w, h = crop.size
    scale = ICON_SIZE / max(w, h)
    nw, nh = max(1, round(w * scale)), max(1, round(h * scale))
    small = crop.resize((nw, nh), Image.LANCZOS)
    canvas = Image.new("RGBA", (ICON_SIZE, ICON_SIZE), (0, 0, 0, 0))
    canvas.paste(small, ((ICON_SIZE - nw) // 2, (ICON_SIZE - nh) // 2), small)
    return canvas


def emit_array(f, name, im):
    a = np.array(im.convert("RGBA"), dtype=np.uint8)
    h, w, _ = a.shape
    flat = a.reshape(-1)
    f.write(f"static const unsigned char {name}[{flat.size}] = {{\n")
    for i in range(0, flat.size, 20):
        f.write(",".join(str(v) for v in flat[i:i + 20]) + ",\n")
    f.write("};\n")


def main():
    wn, wg, wedge_h, tip_frac, icon_cx, icon_cy = load_wedge()
    icons = {name: load_icon(name) for name in ORDER if name != "clavier"}
    icons["clavier"] = load_icon("clavier")

    with open(OUT, "w") as f:
        f.write("// Generated by tools/gen_radial_assets.py — do not edit by hand.\n")
        f.write("// Regenerate after any change to third_party/assets/radial_menu/*.png\n")
        f.write("#ifndef D2VITA_RADIAL_MENU_ASSETS_H\n#define D2VITA_RADIAL_MENU_ASSETS_H\n\n")
        f.write(f"#define RM_N {N}\n")
        f.write(f"#define RM_WEDGE_W {WEDGE_W}\n")
        f.write(f"#define RM_WEDGE_H {wedge_h}\n")
        f.write(f"#define RM_HOLE_RADIUS {HOLE_RADIUS}\n")
        f.write(f"#define RM_ICON_SIZE {ICON_SIZE}\n")
        f.write(f"#define RM_TIP_FRAC {tip_frac:.6f}f\n")
        f.write(f"#define RM_ICON_CX {icon_cx:.6f}f\n")
        f.write(f"#define RM_ICON_CY {icon_cy:.6f}f\n\n")
        emit_array(f, "g_rm_wedge_normal", wn)
        emit_array(f, "g_rm_wedge_glow", wg)
        for name in ORDER:
            emit_array(f, f"g_rm_icon_{name}", icons[name])
        f.write("\nstruct RmSlot { const unsigned char* icon; int vk; const char* name; };\n")
        f.write("static const RmSlot g_rm_slots[RM_N] = {\n")
        for name in ORDER:
            f.write(f'    {{ g_rm_icon_{name}, 0x{VK[name]:02x}, "{name}" }},\n')
        f.write("};\n\n#endif\n")

    print("wedge crop ->", WEDGE_W, "x", wedge_h,
          "TIP_FRAC=%.4f ICON_CX=%.4f ICON_CY=%.4f" % (tip_frac, icon_cx, icon_cy))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
