#!/usr/bin/env python3
# tools/kb_font_gen.py — builds the virtual keyboard's 8x16 font table
# (src/platform/vita_kb.h, g_kb_font95) for printable ASCII 32..126.
#
# The table is a REPRODUCIBLE PRODUCT: it's regenerated by this script from a
# free font present on the machine (DejaVu Sans Mono, Bitstream Vera/DejaVu
# license — free use and redistribution). The font itself isn't embedded:
# only 95 x 16 bytes of rendered pixels, visually checkable with --show.
#   python3 tools/kb_font_gen.py            > C table
#   python3 tools/kb_font_gen.py --show A b : ASCII-art preview
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
W, H, SIZE = 8, 16, 13
BASE = 12          # baseline within the 16-row cell

# Manual touch-ups: at 8px wide, a few glyphs rendered by the font are
# illegible. They live HERE, in the generator, so the table stays fully
# reproducible (regenerating never loses them).
OVERRIDE = {
    "~": [0,0,0,0,0,0,0, 0x78, 0x0f, 0,0,0,0,0,0,0],
}

def glyph(ch):
    if ch in OVERRIDE:
        return list(OVERRIDE[ch])
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    f = ImageFont.truetype(FONT, SIZE)
    try:
        x0, y0, x1, y1 = f.getbbox(ch)
    except Exception:
        x0 = x1 = 0
    x = (W - (x1 - x0)) // 2 - x0
    d.text((x, BASE), ch, font=f, fill=255, anchor="ls")
    rows = []
    px = img.load()
    for y in range(H):
        v = 0
        for xx in range(W):
            if px[xx, y] >= 110:
                v |= 0x80 >> xx
        rows.append(v)
    return rows

def show(chars):
    for ch in chars:
        print(f"--- {ch!r} (0x{ord(ch):02x})")
        for v in glyph(ch):
            print("".join("#" if v & (0x80 >> i) else "." for i in range(8)))

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--show":
        show("".join(sys.argv[2:]) or "Agj@#_.,|")
        sys.exit(0)
    print("// Generated by tools/kb_font_gen.py — do not edit by hand.")
    print("// ASCII 32..126, 8x16, one bit per pixel (msb = column 0).")
    print("static const unsigned char g_kb_font95[95][16] = {")
    for c in range(32, 127):
        ch = chr(c)
        rows = glyph(ch) if ch != " " else [0] * H
        body = ",".join("0x%02x" % v for v in rows)
        # a // comment ENDING in a backslash continues onto the next line and
        # swallows it: the 0x5d entry would silently vanish from the table
        # (an empty glyph at the end of the table).
        name = {0x20: "space", 0x5c: "backslash"}.get(c, ch)
        print("    {%s},  // 0x%02x %s" % (body, c, name))
    print("};")
