// src/platform/radial_menu.h — 7-sector radial menu (hold Select + left
// stick), modeled on platform/vita_kb.h: self-contained header, no VitaSDK,
// draws into the already-rendered frame buffer (GPU or GDI).
//
// Sector-to-D2-key mapping is game policy, so it lives in d2vita rather than
// winx86 (the engine is generic, this binding isn't). See
// radial_menu_assets.h (generated by tools/gen_radial_assets.py) for sector
// order and injected keys.
//
// Geometry follows the asset kit's algorithm (pivot near the wedge's lower
// tip, icon always upright), but the constants (TIP_FRAC, ICON_CX/CY, ratio)
// are measured from the actual pixels of wedge-normal.png by the generator
// script, not copied from the kit's README (whose stated ratio doesn't match
// the shipped files).
//
// Same state model as d2kb: the input tick (game thread) writes state, the
// presentation thread reads it to draw. Benign race (display only), same
// guarantees as the virtual keyboard and frame counter.
#ifndef D2VITA_RADIAL_MENU_H
#define D2VITA_RADIAL_MENU_H

#include <stdint.h>
#include <math.h>
#include "radial_menu_assets.h"

namespace radial_menu {

struct State {
    volatile int open;    // menu is shown (Select held past the tap threshold)
    volatile int active;  // stick is CURRENTLY outside the dead zone (not "was at some point")
    volatile int sel;     // last pointed-at sector (valid only if active)
};

inline void begin(State& s) { s.open = 1; s.active = 0; s.sel = 0; }
inline void end(State& s)   { s.open = 0; s.active = 0; }

// Stick magnitude threshold to pick a sector (wider than the normal movement
// dead zone: requires a deliberate push toward the wheel's edge, not a graze).
constexpr float SELECT_DEADZONE = 0.35f;

// "active" drops back to 0 as soon as the stick returns to center, so
// recentering before releasing Select cancels cleanly instead of firing a
// stale sector. The highlighted sector and the release action both track
// the current state only, never a history.
inline void tick(State& s, float lx, float ly) {
    const float lm = sqrtf(lx * lx + ly * ly);
    if (lm > SELECT_DEADZONE) {
        float ang = atan2f(lx, -ly) * (180.0f / 3.14159265358979f);   // 0 = up, clockwise
        if (ang < 0.0f) ang += 360.0f;
        int idx = (int)(ang / (360.0f / RM_N) + 0.5f) % RM_N;
        if (idx < 0) idx += RM_N;
        s.sel = idx;
        s.active = 1;
    } else {
        s.active = 0;
    }
}

// -1 if the stick is not currently over a sector (centered at release =
// cancel, even if a sector was hovered earlier).
inline int resolved_index(const State& s) { return s.active ? s.sel : -1; }

namespace draw_detail {
inline void kit_rotate(float theta_deg, float x, float y, float* ox, float* oy) {
    const float r = theta_deg * (3.14159265358979f / 180.0f);
    const float c = cosf(r), sn = sinf(r);
    *ox = x * c - y * sn;
    *oy = x * sn + y * c;
}
inline void blend_px(uint32_t* fb, int W, int H, int x, int y,
                      uint8_t r, uint8_t g, uint8_t b, uint8_t a) {
    if (x < 0 || x >= W || y < 0 || y >= H || a == 0) return;
    const size_t o = (size_t)y * W + x;
    if (a == 255) { fb[o] = 0xFF000000u | ((uint32_t)b << 16) | ((uint32_t)g << 8) | r; return; }
    const uint32_t dst = fb[o];
    const uint8_t dr = (uint8_t)(dst & 0xFF), dg = (uint8_t)((dst >> 8) & 0xFF), db = (uint8_t)((dst >> 16) & 0xFF);
    const uint8_t nr = (uint8_t)(((uint32_t)r * a + (uint32_t)dr * (255 - a)) / 255);
    const uint8_t ng = (uint8_t)(((uint32_t)g * a + (uint32_t)dg * (255 - a)) / 255);
    const uint8_t nb = (uint8_t)(((uint32_t)b * a + (uint32_t)db * (255 - a)) / 255);
    fb[o] = 0xFF000000u | ((uint32_t)nb << 16) | ((uint32_t)ng << 8) | nr;
}
// Rotate + alpha blit: samples via the inverse transform inside the rotated
// sprite's world-space bounding box (no fixed canvas to crop, unlike a naive
// in-place rotation).
inline void draw_wedge(uint32_t* fb, int W, int H, const unsigned char* sprite, int sw, int sh,
                        float ax, float ay, float pivot_x, float pivot_y, float theta_deg) {
    const float r = theta_deg * (3.14159265358979f / 180.0f);
    const float ct = cosf(r), st = sinf(r);
    float minx = 1e9f, maxx = -1e9f, miny = 1e9f, maxy = -1e9f;
    const float cxs[4] = {0.f, (float)sw, 0.f, (float)sw};
    const float cys[4] = {0.f, 0.f, (float)sh, (float)sh};
    for (int k = 0; k < 4; ++k) {
        const float lx = cxs[k] - ax, ly = cys[k] - ay;
        const float wx = pivot_x + (lx * ct - ly * st);
        const float wy = pivot_y + (lx * st + ly * ct);
        if (wx < minx) minx = wx; if (wx > maxx) maxx = wx;
        if (wy < miny) miny = wy; if (wy > maxy) maxy = wy;
    }
    int x0 = (int)floorf(minx), x1 = (int)ceilf(maxx);
    int y0 = (int)floorf(miny), y1 = (int)ceilf(maxy);
    if (x0 < 0) x0 = 0; if (y0 < 0) y0 = 0; if (x1 > W) x1 = W; if (y1 > H) y1 = H;
    const float fsw = (float)sw, fsh = (float)sh;   // hoisted: the inner test runs per pixel
    for (int y = y0; y < y1; ++y) {
        for (int x = x0; x < x1; ++x) {
            const float wx = (float)x + 0.5f - pivot_x, wy = (float)y + 0.5f - pivot_y;
            const float lxp = wx * ct + wy * st;          // R(-theta) = R^T (orthonormal rotation)
            const float lyp = -wx * st + wy * ct;
            // Source pixel WITHOUT floorf(): ARMv7 has no floor instruction,
            // so floorf() is a library call — and this loop made two of them
            // per pixel, ~160 000 pixels per frame, on the thread that
            // presents. The range test below is the very test floor() would
            // have passed (floor(v) < 0 <=> v < 0, and floor(v) >= n <=>
            // v >= n); once it holds the value is non-negative, and there the
            // plain cast IS floor. Same pixels, no call — see
            // tools/oracle_radial.sh.
            const float sx = lxp + ax, sy = lyp + ay;
            if (sx < 0.0f || sx >= fsw || sy < 0.0f || sy >= fsh) continue;
            const unsigned char* p = sprite + ((size_t)(int)sy * sw + (int)sx) * 4;
            blend_px(fb, W, H, x, y, p[0], p[1], p[2], p[3]);
        }
    }
}
inline void draw_icon(uint32_t* fb, int W, int H, const unsigned char* icon, int isz, float cx, float cy) {
    const int x0 = (int)floorf(cx - isz * 0.5f), y0 = (int)floorf(cy - isz * 0.5f);
    for (int y = 0; y < isz; ++y)
        for (int x = 0; x < isz; ++x) {
            const unsigned char* p = icon + ((size_t)y * isz + x) * 4;
            blend_px(fb, W, H, x0 + x, y0 + y, p[0], p[1], p[2], p[3]);
        }
}
} // namespace draw_detail

// Draws nothing if the menu is closed (same rule as d2kb).
inline void draw(const State& s, uint32_t* fb, int scr_w, int scr_h) {
    using namespace draw_detail;
    if (!fb || !s.open) return;
    const float cx = scr_w * 0.5f, cy = scr_h * 0.5f;
    const float ax = 0.5f * RM_WEDGE_W, ay = RM_TIP_FRAC * RM_WEDGE_H;
    for (int i = 0; i < RM_N; ++i) {
        const float theta = i * (360.0f / RM_N);
        float dx, dy; kit_rotate(theta, 0.0f, -(float)RM_HOLE_RADIUS, &dx, &dy);
        const float pivot_x = cx + dx, pivot_y = cy + dy;
        const bool sel = s.active && (i == s.sel);
        draw_wedge(fb, scr_w, scr_h, sel ? g_rm_wedge_glow : g_rm_wedge_normal,
                   RM_WEDGE_W, RM_WEDGE_H, ax, ay, pivot_x, pivot_y, theta);
        float idx, idy;
        kit_rotate(theta, (RM_ICON_CX - 0.5f) * RM_WEDGE_W, (RM_ICON_CY - RM_TIP_FRAC) * RM_WEDGE_H, &idx, &idy);
        draw_icon(fb, scr_w, scr_h, g_rm_slots[i].icon, RM_ICON_SIZE, pivot_x + idx, pivot_y + idy);
    }
}

} // namespace radial_menu
#endif // D2VITA_RADIAL_MENU_H
